format:
  html: {toc: true, toc-depth: 4, theme: cosmo, number-sections: false}
  revealjs: {theme: cosmo, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, notebooks/question_1.ipynb, notebooks/question_2.ipynb, notebooks/technical_report.md]
  title: 'CS7300: Practical Midterm'
